### ISSUE TITLE
Add a delay for pages with transitions

### ISSUE THREAD

**Issue by yratof** [ClockworkNet/watircats#1]
Using AJAX, I can't take screenshots of a website because there is a 1 second delay between the pages. 

Should there be an option to add a delay to the page before a screenshot?

**Comment by sonjaq** [comment]
There is now in the source. Sorry it took so long and the implementation was sloppy, but, there's now a `--delay` parameter that you can apply to every page load, after the document reports `complete` for its `readyState`.

**Comment by yratof** [comment]
Fantastic – Thank you!
